# Generated by Django 4.2.7 on 2023-12-16 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voice',
            new_name='Vote',
        ),
    ]
